CREATE TABLE TEAM (
    TEAM_ID VARCHAR(30) PRIMARY KEY,
    ORIGIN_YYYY DATE,
    REGION_NANE VARCHAR2(30),
    DIRECTOR VARCHAR2(30),
    WEBPAGE VARCHAR2(30),
    ADDRESS VARCHAR2 (30),
    ZIP_CODE1 NUMBER,
    ZIP_CODE2 NUMBER,
    DDD VARCHAR2(30),
    TEL NUMBER,
    FAX NUMBER,
    OWNER VARCHAR2(30),
    STADIUM_ID VARCHAR2(30)
);


CREATE TABLE PLAYER(
    PLAYER_ID VARCHAR2(30) PRIMARY KEY,
    PLAYER_NAME VARCHAR2(30),
    TEAM_ID VARCHAR2(30),
    E_PLAYER_NAME VARCHAR2(30),
    NICKNAME VARCHAR2(30),
    JOIN_YYYY DATE,
    POSITION VARCHAR2(30),
    BACK_NO NUMBER,
    NATION VARCHAR2(30),
    BIRTH_DATE DATE,
    SOLAR VARCHAR2(30),
    HEIGHT NUMBER,
    WEIGHT NUMBER
);

CREATE TABLE STADIUM(
    STADIUM_ID VARCHAR2(30) PRIMARY KEY,
    STADIUM_NAME VARCHAR2(30),
    HOMETEAM_ID VARCHAR2(30),
    SEAT_COUNT NUMBER,
    ADDRESS VARCHAR2(30),
    DDD VARCHAR2(30),
    TEL NUMBER,
    TEAM_ID VARCHAR2(30)
);

CREATE TABLE SCHEDULE(
    SCHE_DATE DATE PRIMARY KEY,
    STADIUM_ID VARCHAR2(30),
    GUBUN NUMBER,
    HOMETEAM_ID VARCHAR2(30),
    AWAYTEAM_ID VARCHAR2(30),
    HOME_SCORE NUMBER,
    AWAY_SCORE NUMBER
);



